Done
AleksandrOnis/REST-API-application pull request #3
Opened 2022-02-06 20:45 UTC by AleksandrOnis

2022-02-07 11:45 UTC, Danil44 commented
навіщо нам jws папка?

2022-02-07 11:48 UTC, Danil44 requested changes

2022-02-07 11:48 UTC, Danil44 commented on routes/api/auth.js
> +router.post("/signup", async (req, res, next) => {
Ліпше виносити реалізацію в окремі папки та файли

2022-02-09 21:31 UTC, AleksandrOnis commented
jws папка - не знаю (( - мабуть перед пулом випадково витягнув з папки node_modules
Добавив контроллери.

2022-02-10 18:31 UTC, merged